/**
 * Content Script for Phishing Detection
 * Displays warning overlays when phishing is detected
 */

// Track if warning is already shown
let warningShown = false;

/**
 * Create and display phishing warning overlay
 */
function showPhishingWarning(data) {
    // Don't show multiple warnings
    if (warningShown) {
        return;
    }

    warningShown = true;

    // Create overlay
    const overlay = document.createElement('div');
    overlay.id = 'phishing-warning-overlay';

    // Create content
    const content = `
        <div id="phishing-warning-content">
            <div id="phishing-warning-header">
                <div id="phishing-warning-icon">⚠️</div>
                <h1 id="phishing-warning-title">Phishing Warning!</h1>
                <p id="phishing-warning-subtitle">This website may be trying to steal your information</p>
            </div>

            <div id="phishing-warning-details">
                <div id="phishing-warning-url">
                    <strong>Suspicious URL:</strong><br>
                    ${escapeHtml(window.location.href)}
                </div>

                <div id="phishing-warning-confidence">
                    Detection Confidence: ${data.confidencePercent}%
                </div>

                ${data.explanations && data.explanations.length > 0 ? `
                    <div id="phishing-warning-reasons">
                        <h3>Why this was flagged:</h3>
                        <ul>
                            ${data.explanations.map(exp => `<li>${escapeHtml(exp)}</li>`).join('')}
                        </ul>
                    </div>
                ` : ''}
            </div>

            <div id="phishing-warning-actions">
                <button id="phishing-warning-back" class="phishing-warning-btn">
                    Go Back to Safety
                </button>
                <button id="phishing-warning-proceed" class="phishing-warning-btn">
                    Proceed Anyway (Not Recommended)
                </button>
            </div>

            <div id="phishing-warning-disclaimer">
                ${data.detectionType === 'combined' ? `
                    This warning uses combined URL + Page analysis (${data.confidencePercent}% confidence).<br>
                    URL: ${data.urlPrediction.phishingPercent || data.urlPrediction.confidencePercent}% phishing${data.urlPrediction.domainPhishingPercent !== undefined ? ` (Domain: ${data.urlPrediction.domainPhishingPercent}%, Path: ${data.urlPrediction.pathPhishingPercent}%)` : ''} | Page: ${data.pagePrediction.phishingPercent || data.pagePrediction.confidencePercent}% phishing
                ` : data.detectionType === 'url' || data.detectionType === 'url_only' ? `
                    This warning is based on URL analysis only (${data.confidencePercent}% confidence).
                ` : `
                    This warning is generated by machine learning (${data.confidencePercent}% confidence).
                `}
                <br>While our models have high accuracy, false positives may occur.
            </div>
        </div>
    `;

    overlay.innerHTML = content;

    // Add to page
    document.body.appendChild(overlay);

    // Add event listeners
    document.getElementById('phishing-warning-back').addEventListener('click', () => {
        window.history.back();
    });

    document.getElementById('phishing-warning-proceed').addEventListener('click', () => {
        overlay.remove();
        warningShown = false;

        // Store user's decision
        chrome.storage.local.set({
            [`dismissed_${window.location.href}`]: Date.now()
        });
    });

    // Prevent clicking through overlay
    overlay.addEventListener('click', (e) => {
        if (e.target === overlay) {
            e.stopPropagation();
        }
    });
}

/**
 * Escape HTML to prevent XSS
 */
function escapeHtml(text) {
    const div = document.createElement('div');
    div.textContent = text;
    return div.innerHTML;
}

/**
 * Check if warning was previously dismissed
 */
async function wasWarningDismissed() {
    return new Promise((resolve) => {
        chrome.storage.local.get(`dismissed_${window.location.href}`, (result) => {
            const dismissedTime = result[`dismissed_${window.location.href}`];
            if (dismissedTime) {
                // Check if dismissed within last 24 hours
                const hoursSinceDismissal = (Date.now() - dismissedTime) / (1000 * 60 * 60);
                resolve(hoursSinceDismissal < 24);
            } else {
                resolve(false);
            }
        });
    });
}

/**
 * Listen for messages from background script
 */
chrome.runtime.onMessage.addListener(async (request, sender, sendResponse) => {
    if (request.type === 'COMBINED_RESULT') {
        console.log('Combined analysis result:', request.data);

        // Update badge with combined result
        const status = request.data.isPhishing ? 'suspicious' : 'safe';
        addSecurityBadge(status, request.data.confidencePercent);
    }

    if (request.type === 'PHISHING_DETECTED') {
        console.log('Phishing detected by background script:', request.data);

        // Check if user previously dismissed this warning
        const dismissed = await wasWarningDismissed();
        if (!dismissed) {
            showPhishingWarning(request.data);
        } else {
            console.log('Warning previously dismissed by user');
        }
    }
});

/**
 * Add small indicator badge to page
 */
function addSecurityBadge(status, confidence) {
    // Remove existing badge if any
    const existing = document.getElementById('phishing-detector-badge');
    if (existing) {
        existing.remove();
    }

    const badge = document.createElement('div');
    badge.id = 'phishing-detector-badge';
    badge.style.cssText = `
        position: fixed;
        bottom: 20px;
        right: 20px;
        background: ${status === 'safe' ? '#28a745' : '#dc3545'};
        color: white;
        padding: 10px 15px;
        border-radius: 25px;
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
        font-size: 12px;
        font-weight: 600;
        box-shadow: 0 4px 12px rgba(0,0,0,0.2);
        z-index: 999998;
        cursor: pointer;
        transition: all 0.3s ease;
    `;

    badge.innerHTML = `
        ${status === 'safe' ? '✅' : '⚠️'}
        ${status === 'safe' ? 'Safe Site' : 'Suspicious Site'}
        (${confidence}%)
    `;

    badge.addEventListener('mouseenter', () => {
        badge.style.transform = 'scale(1.05)';
    });

    badge.addEventListener('mouseleave', () => {
        badge.style.transform = 'scale(1)';
    });

    badge.addEventListener('click', () => {
        // Open extension popup
        chrome.runtime.sendMessage({ type: 'OPEN_POPUP' });
    });

    document.body.appendChild(badge);

    // Auto-hide safe badge after 5 seconds
    if (status === 'safe') {
        setTimeout(() => {
            badge.style.opacity = '0';
            setTimeout(() => badge.remove(), 300);
        }, 5000);
    }
}

/**
 * Extract page features and send to background for prediction
 */
async function analyzePageFeatures() {
    try {
        const startTime = performance.now();

        // Extract page features
        const extractor = new PageFeatureExtractor();
        const features = extractor.extractAll();

        const extractionTime = performance.now() - startTime;
        console.log(`Page features extracted in ${extractionTime.toFixed(2)}ms`);
        console.log('Page features:', features);

        // Send features to background script for prediction
        chrome.runtime.sendMessage({
            type: 'PAGE_FEATURES',
            features: features,
            url: window.location.href
        });
    } catch (error) {
        console.error('Error analyzing page features:', error);
    }
}

/**
 * Request analysis on page load
 */
window.addEventListener('load', () => {
    // Don't analyze chrome:// pages or extension pages
    if (window.location.href.startsWith('chrome://') ||
        window.location.href.startsWith('chrome-extension://')) {
        return;
    }

    // Request URL analysis from background script
    chrome.runtime.sendMessage({
        type: 'ANALYZE_URL',
        url: window.location.href
    }, (response) => {
        if (response && !response.error) {
            console.log('URL analysis result:', response);

            // Add security badge (will be updated when combined result is ready)
            const status = response.isPhishing ? 'suspicious' : 'safe';
            addSecurityBadge(status, response.confidencePercent);
        }
    });

    // Wait a bit for DOM to fully stabilize, then analyze page features
    setTimeout(() => {
        analyzePageFeatures();
    }, 500);
});

console.log('Phishing Detection Extension: Content script loaded');
